swagger: '2.0'
info:
  title: Saladio API
  description: Backend to provide various functionalities to clients
  version: "1.0.0"
host: 127.0.0.1:10010
schemes:
  - http
basePath: /v1
produces:
  - application/json
definitions:
  SaladComponent:
    type: object
    required:
      - name
      - weight
      - callorie
      - price
    properties:
      name:
        type: string
        description: Name of salad component
      weight:
        type: number
        description: Effect of 1 unit of component on total weight of the salad (in gramms)
      callorie:
        type: number
        description: Effect of 1 unit of component on total salad callorie (in K callorie)
      price:
        type: number
        description: Effect of 1 unit of component on total salad price (in Rials)
  SaladComponentGroup:
    type: object
    properties:
      name:
        type: string
        description: Name of salad component group
      items:
        type: array
        items:
          $ref: '#/definitions/SaladComponent'
parameters:
  listStart:
    name: start
    in: query
    type: integer
    description: starting offset to fetch list
    required: true
    minimum: 0
  listLength:
    name: length
    in: query
    type: integer
    description: number of items to fetch from list
    required: true
    minimum: 0
paths:
  /SaladComponentGroup:
    x-swagger-router-controller: saladComponentGroup
    get:
      description: Returns list of salad components to build custom salads
      operationId: getSaladComponentGroup
      parameters:
        - $ref: "#/parameters/listStart"
        - $ref: "#/parameters/listLength"
      responses:
        200:
          description: A list of salad components
          schema:
            type: object
            properties:
              recordsFiltered:
                type: integer
                description: numeber of filtered records
              recordsTotal:
                type: integer
                description: total number of rows
              data:
                type: array
                items:
                  $ref: '#/definitions/SaladComponentGroup'
  /hello/{user}:
    get:
      description: Returns a greeting to the user!
      parameters:
        - name: user
          in: path
          type: string
          required: true
          description: The name of the user to greet.
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.
          

