swagger: '2.0'
info:
  title: Saladio API
  description: Backend to provide various functionalities to clients
  version: "1.0.0"
host: 127.0.0.1:10010
schemes:
  - http
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
responses:
  Conflict:
    description: usually occurs when target resource exists or is already in requested state
    schema:
      $ref: '#/definitions/SystemError'
  InternalServerError:
    description: occurs when system is interrupted by an unexpected exception or internal error
    schema:
      $ref: '#/definitions/SystemError'
securityDefinitions:
  basic:
    type: basic
    description: these APIs use basic HTTP authentication
definitions:
  SystemError:
    type: object
    description: encapsulates system error messages
    properties:
      code:
        type: integer
        description: an integer that may show more insight about occurred error
      message:
        type: string
        description: a text message that may show more insight about occured error
      stack:
        type: string
        description: if debugging is disabled, will show stack trace of occured error
    example:
      code: -1
      message: 'internal server error occured'
      stack: 'error at a.js line 23...'
  SaladComponent:
    type: object
    description: specifies a component used in ordering a custom salad
    required:
      - name
      - weight
      - callorie
      - price
    properties:
      id:
        type: integer
        description: identifier of salad component
        minimum: 0
      name:
        type: string
        description: Name of salad component
        minLength: 1
      weight:
        type: number
        description: Effect of 1 unit of component on total weight of the salad (in gramms)
        minimum: 0
      callorie:
        type: number
        description: Effect of 1 unit of component on total salad callorie (in K callorie)
        minimum: 0
      price:
        type: number
        description: Effect of 1 unit of component on total salad price (in Rials)
        minimum: 0
    example:
      id: 10
      name: 'kahoo'
      weight: 0.2
      callorie: 0.4
      price: 1024.5
  SaladComponentGroup:
    type: object
    description: shows collection of custom salad components bundled together
    properties:
      name:
        type: string
        description: Name of salad component group
        minLength: 1
      items:
        type: array
        items:
          $ref: '#/definitions/SaladComponent'
    example:
      name: 'sabzijat'
      items:
        - name: 'kahoo'
          weight: 0.2
          callorie: 0.4
          price: 1024.5
  PersianDate:
    type: object
    description: represents a jalali date
    required:
      - year
      - month
      - day
    properties:
      year:
        type: integer
        description: Jalali year
        minimum: 1300
        maximum: 1500
        default: 1395
      month:
        type: integer
        description: month of year, starting from 1
        minimum: 1
        maximum: 12
        default: 9
      day:
        type: integer
        description: day of month, starting from 1
        minimum: 1
        maximum: 31
        default: 27
    example:
      year: 1395
      month: 9
      day: 25
  Email:
    type: string
    description: email address of user
    pattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    default: saladio@domain.com
  PhoneNumber:
    type: string
    description: mobile (cell) phone number of user
    pattern: '^(\+?989\d{2}|09\d{2})\d{7}$'
    default: '09123334444'
  User:
    type: object
    description: encapsulates information about a registered user
    required:
      - email
      - phoneNumber
      - firstName
      - lastName
      - gender
      - birthDate
      - addresses
    properties:
      userName:
        type: string
        description: Username
      email:
        $ref: '#/definitions/Email'
      phoneNumber:
        $ref: '#/definitions/PhoneNumber'
      password:
        type: string
        description: chosen password for user
        minLength: 8
        default: '12345678'
      firstName:
        type: string
        description: user firstname
        minLength: 1
        default: 'saladio'
      lastName:
        type: string
        description: user lastname
        minLength: 1
        default: 'chef'
      birthDate:
        $ref: '#/definitions/PersianDate'
      gender:
        type: string
        description: gender of user
        default: 'female'
        enum:
          - male
          - female
      weight:
        type: number
        description: weight of registered user (kg)
        minimum: 1
        maximum: 300
        default: 56
      addresses:
        type: array
        description: User delivery addresses
        minLength: 1
        default:
          - saadat abad, majd, pelak 2, vahed 27
        items:
          type: string
          minLength: 1
    example:
      userName: saladio@domain.com
      email: saladio@domain.com
      phoneNumber: '09123338888'
      password: '12345678'
      firstName: saladio
      lastName: chef
      birthDate:
        year: 1395
        month: 9
        day: 25
      gender: female
      weight: 56
      addresses:
        - saadat abad, majd, pelak 2, vahed 27
  URL:
    type: string
    description: represents an internet resource
    pattern: '^(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'
  Salad:
    type: object
    description: |
      acts as a base class for all saved salads (classics and user ordered)
    required:
      - name
    properties:
      id:
        type: integer
        description: a hidden system id
        minimum: 0
      name:
        type: string
        description: name of salad
        minLength: 1
        default: my salad
      description:
        type: string
        description: A brief description about salad
      picture:
        $ref: '#/definitions/URL'
      callorie:
        type: number
        description: total callorie of salad (in K callorie)
        minimum: 0
      weight:
        type: number
        description: total weight of salad (in gramms)
        minimum: 0
      price:
        type: integer
        description: total price of salad (in rials)
        minimum: 0
  PickedSaladComponent:
    type: object
    description: |
      represents user choice about how many
      components to user in a custom salad
    required:
      - saladComponentId
      - quantity
    properties:
      saladComponentId:
        type: integer
        description: id of salad component
        minimum: 0
      quantity:
        type: integer
        description: number of units picked
        minimum: 0
  SavedSalad:
    description: represents a user saved saved salad
    allOf:
      - $ref: '#/definitions/Salad'
      - type: object
        required:
          - ingredients
        properties:
          ingredients:
            type: array
            description: salad components
            minLength: 1
            items:
              $ref: '#/definitions/PickedSaladComponent'
  ClassicSalad:
    description: represents a pre-defined salad
    allOf:
      - $ref: '#/definitions/Salad'
      - type: object
        required:
          - longDescription
          - ingredients
        properties:
          longDescription:
            type: string
            description: |
              denotes more descriptive long description of
              salad possibly a paragraph or two
            minLength: 1
          ingredients:
            type: string
            description: shows ingredients used in salad
            minLength: 1
  DeliverySchedule:
    description: represents delivery schedules
    type: object
    required:
      - catagory
      - fromHour
      - toHour
    properties:
      id:
        type: integer
        description: id of delivery schedule
        minimum: 0
      catagory:
        type: string
        description: whether it is launch or dinner
        enum:
          - launch
          - dinner
        default: launch
      fromHour:
        type: integer
        description: start hour of delivery range
        minimum: 8
        maximum: 24
        default: 11
      toHour:
        type: integer
        description: end hour of delivery range
        minimum: 8
        maximum: 24
        default: 12
  Order:
    type: object
    description: represents a salad order
    required:
      - saladId
      - deliveryDate
      - deliveryScheduleId
      - address
      - price
    properties:
      id:
        type: integer
        description: id of order
        minimum: 0
      saladId:
        type: integer
        description: which salad which has been selected
        minimum: 0
      deliveryDate:
        $ref: '#/definitions/PersianDate'
      deliveryScheduleId:
        type: integer
        description: which shipping hour user has selected
        minimum: 0
      address:
        type: string
        description: delivery address
        minLength: 1
      price:
        type: integer
        description: price of salad in rials
        minimum: 0
parameters:
  listStart:
    name: start
    in: query
    type: integer
    description: starting offset to fetch list
    required: true
    minimum: 0
    default: 0
  listLength:
    name: length
    in: query
    type: integer
    description: number of items to fetch from list
    required: true
    minimum: 0
    default: 10
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /SaladComponentGroups:
    x-swagger-router-controller: saladComponentGroup
    get:
      description: Returns list of salad components to build custom salads
      operationId: getSaladComponentGroup
      parameters:
        - $ref: '#/parameters/listStart'
        - $ref: '#/parameters/listLength'
      security:
        - basic: []
      responses:
        200:
          description: A list of salad components
          schema:
            type: object
            properties:
              recordsFiltered:
                type: integer
                description: numeber of filtered records
              recordsTotal:
                type: integer
                description: total number of rows
              data:
                type: array
                items:
                  $ref: '#/definitions/SaladComponentGroup'
        500:
          $ref: '#/responses/InternalServerError'
  /Users:
    x-swagger-router-controller: user
    put:
      description: register a new user in the system
      operationId: signup
      parameters:
        - name: signup
          in: body
          description: information about user to signup
          schema: 
            $ref: '#/definitions/User'
          required: true
      responses:
        200:
          description: indicates that user is signedup successfuly
          schema:
            type: object
            properties:
              userName:
                type: string
                description: username of newly added user
                minLength: 1
        409:
          $ref: '#/responses/Conflict'
        500:
          $ref: '#/responses/InternalServerError'
  /SavedSalads:
    x-swagger-router-controller: savedSalad
  
          

