#%RAML 0.8
---

title: Saladio BackEnd Server
baseUri: http://api.saladio.ir/{version}
version: v1
mediaType: application/json
protocols:
  - HTTP

securitySchemes:
  - basic:
      description: Client provides user/password upon API invokation
      type: Basic Authentication

securedBy:
  - basic

schemas:
  - SaladComponent: |
      {
        "type": "object",
        "$shema": "http://json-schema.org/draft-03/schema",
        "id": "SaladComponent",
        "properties": {
            "name": {
              "type": "string",
              "required": true,
              "description": "Name of salad component"
            },
            "weight": {
              "type": "number",
              "required": true,
              "description": "Effect of 1 unit of component on total weight of the salad (in gramms)",
              "minimum": 0
            },
            "callorie": {
              "type": "number",
              "required": true,
              "description": "Effect of 1 unit of component on total salad callorie (in K callorie)",
              "minimum": 0
            },
            "price": {
              "type": "number",
              "required": true,
              "description": "Effect of 1 unit of component on total salad price (in Rials)",
              "minimum": 0
            }
        }
      }
  - SaladComponentGroup: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "SaladComponentGroup",
        "properties": {
            "name": {
                "type": "string",
                "required": true,
                "description": "Name of salad component group",
                "minLength": 1
            }
        }
      }
  - SystemMessage: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "SystemMessage",
        "properties": {
          "errorCode": {
            "type": "number",
            "description": "A number denoting internal error which has occured",
            "required": true,
            "default": -1
          },
          "message": {
            "type": "string",
            "description": "A textual representation of error or an exception stack trace",
            "required": true,
            "default": ""
          }
        }
      }

resourceTypes:
  - Collection:
      usage: Represents a generic CRUD collection
      description: Represens a collection of <<resourcePathName | !singularize>>
      get:
        queryParameters:
          start:
            description: offset of items to fetch
            displayName: Start
            type: integer
            minimum: 0
            required: true
          length:
            description: total number of items to fetch starting `{start}`
            displayName: Length
            type: integer
            minimum: 0
            required: true
        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "type": object,
                    "$schema": "http://json-schema.org/draft-03/schema",
                    "id": "CollectionResponse",
                    "properties": {
                      "recordsTotal": {
                        "type": "integer",
                        "required": true,
                        "minimum": 0,
                        "description": "total number of records in collection without considering user search criteria"
                      },
                      "recordsFiltered": {
                        "type": "integer",
                        "required": true,
                        "minimum": 0,
                        "description": "total number of records which are filtered by user input"
                      },
                      "items": {
                        "type": "array",
                        "required": true,
                        "items": {
                          "$ref": "#<<resourcePathName | !singularize>>"
                        }
                      }
                    }
                  }
      put:
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName | !singularize>>
          409:
            body:
              application/json:
                schema: SystemMessage
          401:
            body:
              application/json:
                schema: SystemMessage
  - CollectionItem:
      usage: Represents a generic CRUD operation on single item
      description: Represents items in <<resourcePathName>> collection
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName | !singularize>>
          404:
            body:
              application/json:
                schema: SystemMessage
      patch:
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            body:
              application/json:
                schema: SystemMessage
          409:
            body:
              application/json:
                schema: SystemMessage
          401:
            body:
              application/json:
                schema: SystemMessage
      delete:
        responses:
          200:
            body:
              application/json:
                schema: SystemMessage
          409:
            body:
              application/json:
                schema: SystemMessage
          401:
            body:
              application/json:
                schema: SystemMessage

/SaladComponentGroups:
  type: Collection
  /{groupName}:
    type: CollectionItem
